### ISSUE TITLE
Use ^3.2 as version constraint for Sculpin

### ISSUE THREAD

**Issue by lhsazevedo** [clue/clue.engineering#131]
Back in #123, Sculpin was updated to the development version `dev-master#23a74ba` to obtain a fix regarding PHP 8 compatibility that wasn't released at the time. Now Sculpin 3.2 is already available and `^3.2` can safely be used as version constraint.

May I open this PR? :)

**Comment by SimonFrings** [comment]
Hey @lhsazevedo, good catch! :+1: 

> May I open this PR? :)

Of course, we're always happy about contributions to our projects.
