### ISSUE TITLE
Unable to login to github in Firefox.

### ISSUE THREAD

**Issue by sitedyno** [clue/clue.engineering#25]
I disabled all blocking (Firefox and ad-blocker) and still get the following:

[Blocked by Content Security Policy](https://imgur.com/bXMbRw4)

This warning appears in the console:
```Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.```

**Comment by clue** [comment]
@sitedyno Thanks for reporting, but unfortunately I can not reproduce this locally.

Can you give more specific instructions on how to reproduce this? I've just tested accessing the blog and logging in to leave a comment with Firefox 64 on Ubuntu 19.04 and can not see any problems.

**Comment by sitedyno** [comment]
This is with Firefox 69 on Manjaro. I scrolled to  the bottom of the new blog engine post and clicked on the smiley face icon in your comment to add a reaction. There is a link to "[Sign in](https://api.utteranc.es/authorize?redirect_uri=https%3A%2F%2Fclue.engineering%2F2019%2Fnew-blog) to add your reaction." Clicking that link results in the blocking/warning as described above.

**Comment by clue** [comment]
@sitedyno Thanks for getting back to this, I can now reproduce the problem you're seeing and have just filed an upstream PR to fix this: https://github.com/utterance/utterances/pull/201

In the meantime, you can use the green 'Sign in to comment' button at the bottom to sign in. Once you're signed in, you can also leave a reaction without having to post a comment.

I will keep this ticket updated once that PR makes some progress :+1:

**Comment by sitedyno** [comment]
Works for me now :100:
